In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.svm import SVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix




In [ ]:
df = pd.read_csv("SMSSpamCollection",sep = '\t',names = ['label','message'])
df = df[['label','message']]

df.columns = ['labels','text']

df['labels'] = df['labels'].map({'ham':0,'spam':1})
df.head()

x_train,x_test,y_train,y_test = train_test_split(df['text'],df['labels'],test_size=0.2,random_state=42)

vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=3000
)

x_train_vectorizer = vectorizer.fit_transform(x_train)
x_test_vectorizer = vectorizer.transform(x_test)

lr = LogisticRegression()
lr.fit(x_train_vectorizer,y_train)

y_pred = lr.predict(x_test_vectorizer)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))




              precision    recall  f1-score   support

           0       0.98      1.00      0.99       966
           1       1.00      0.84      0.91       149

    accuracy                           0.98      1115
   macro avg       0.99      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115

[[966   0]
 [ 24 125]]


labels    0
text      0
dtype: int64

In [ ]:
df = pd.read_csv("SMSSpamCollection",sep = '\t',names = ['label','message'])
df = df[['label','message']]

df.columns = ['labels','text']

df['labels'] = df['labels'].map({'ham':0,'spam':1})
df.head()

x_train,x_test,y_train,y_test = train_test_split(df['text'],df['labels'],test_size=0.2,random_state=42)

vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=3000
)

x_train_vectorizer = vectorizer.fit_transform(x_train)
x_test_vectorizer = vectorizer.transform(x_test)

param_grid = {'n_neighbors':[3,5,7,9],'metric':['euclidean','manhattan']}
grid_search = GridSearchCV(KNeighborsClassifier(weights='distance'), param_grid, cv = 5, scoring='f1',n_jobs=-1)

grid_search.fit(x_train_vectorizer,y_train)
best_model = grid_search.best_estimator_

y_pred = best_model.predict(x_test_vectorizer)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))




              precision    recall  f1-score   support

           0       0.95      1.00      0.97       966
           1       1.00      0.64      0.78       149

    accuracy                           0.95      1115
   macro avg       0.97      0.82      0.88      1115
weighted avg       0.95      0.95      0.95      1115

[[966   0]
 [ 54  95]]


In [ ]:
df = pd.read_csv("SMSSpamCollection",sep = '\t',names = ['label','message'])
df = df[['label','message']]

df.columns = ['labels','text']

df['labels'] = df['labels'].map({'ham':0,'spam':1})
df.head()

x_train,x_test,y_train,y_test = train_test_split(df['text'],df['labels'],test_size=0.2,random_state=42)

vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=3000
)

x_train_vectorizer = vectorizer.fit_transform(x_train)
x_test_vectorizer = vectorizer.transform(x_test)

param_grid = {'max_depth':[10,15,20],'min_samples_split':[5,10,15],'min_samples_leaf':[5,10,15]}
grid_search = GridSearchCV(DecisionTreeClassifier(class_weight='balanced'), param_grid, cv = 5, scoring='f1',n_jobs=-1)

grid_search.fit(x_train_vectorizer,y_train)
best_model = grid_search.best_estimator_

y_pred = best_model.predict(x_test_vectorizer)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))




              precision    recall  f1-score   support

           0       0.98      0.94      0.96       966
           1       0.71      0.90      0.79       149

    accuracy                           0.94      1115
   macro avg       0.85      0.92      0.88      1115
weighted avg       0.95      0.94      0.94      1115

[[911  55]
 [ 15 134]]


In [ ]:
df = pd.read_csv("SMSSpamCollection",sep = '\t',names = ['label','message'])
df = df[['label','message']]

df.columns = ['labels','text']

df['labels'] = df['labels'].map({'ham':0,'spam':1})
df.head()

x_train,x_test,y_train,y_test = train_test_split(df['text'],df['labels'],test_size=0.2,random_state=42)

vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=3000
)

x_train_vectorizer = vectorizer.fit_transform(x_train)
x_test_vectorizer = vectorizer.transform(x_test)

param_grid = {'C':[0.1,1,10],'gamma':[0.001,0.1],}
grid_search = GridSearchCV(SVC(class_weight= 'balanced'), param_grid, cv = 5, scoring='f1',n_jobs=-1)

grid_search.fit(x_train_vectorizer,y_train)
best_model = grid_search.best_estimator_

y_pred = best_model.predict(x_test_vectorizer)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))




              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.97      0.94      0.95       149

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

[[961   5]
 [  9 140]]
